Restaurant page
erezfree29/Restaurant pull request #2
Opened 2021-06-16 11:03 UTC by erezfree29

Restaurant page
Done in accordance with the Udin project Restaurant exercise.
skills applied 
1)NPM
2)Webpack
3)Javascript
4)Functions exporting.
5)Css
Only one basic Html file is used while the content is written and wiped out using purely JavaScript

2021-06-16 12:00 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- It uses Webpack :+1: 

To improve :factory_worker: [REQUIRED]:

- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. .vscode and draft.html) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] It includes a rule for the node_modules directory on .gitignore ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/gitignore_requirement_pathwright.png) from [Odin](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
- [ ] As you are using ES6 syntax, please use `arrow functions `instead of `the function keyword`  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
- [ ] The contents of each tab are stored in a module. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/tab_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
- [ ] Please check your readme by using Grammarly because it is the first thing that the user reads

Nice to have [OPTIONAL] :

- [ ] 

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-06-16 12:00 UTC, rindrajosia commented on README.md
> +In order to run the the project on your local machine, please run the following commands on your terminal:
In order to run `the project` on your local machine, please run the following commands on your terminal:

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/contact.js
> +function contact() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/description.js
> +function description() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/header.js
> +function headline() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/home.js
> +function home() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/index.js
> +homeButton.onclick = function () {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/index.js
> +contactButton.onclick = function () {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/index.js
> +menuButton.onclick = function () {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/menu.js
> +function menu() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/navbar.js
> +function navBar() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/picture.js
> +function pictureDiv() {
usage of arrow functions instead of the function keyword

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/index.js
> +  `;
The contents of each tab are stored in a module.

2021-06-16 12:00 UTC, rindrajosia commented on src/scripts/index.js
> +  `;
The contents of each tab are stored in a module.

2021-06-16 16:24 UTC, mikenath223 requested changes
### Hello @erezfree29  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

To highlight: 
- Fix the module export in the app.
- Use es6 arrow functions.

- Please refer to other comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-16 16:38 UTC, mikenath223 commented on src/scripts/homebuttonpage.js
> +export default homebuttonpage();
- [ ] This isn't the right way to export a module. Do this instead: `export default homebuttonpage;`. **Fix all other exported modules also.**

2021-06-16 16:40 UTC, mikenath223 commented on src/scripts/index.js
> +import menuButtonPage from './menubuttonpage';
- [ ] After importing the modules you can call them this way: `homeButtonPage()`, As they are functions. Then simply write logic here to call a function when the particular nav item is clicked.

2021-06-16 16:41 UTC, mikenath223 commented on src/scripts/menubuttonpage.js
> +      content.parentNode.removeChild(content);
- [ ] Please change this and **all** other regular functions to es6 arrow function syntax.

2021-06-16 16:43 UTC, mikenath223 commented on src/scripts/homebuttonpage.js
> +    const contactContent = document.querySelector('.contact_content');
- [ ] This isn't the right way to export a module. Do this instead: `export default homebuttonpage;`. **Fix all other exported modules also.**

2021-06-16 16:46 UTC, mikenath223 commented
- [ ] There was a large subset of changes so kindly refer to the comments above as the review. Thanks

2021-06-16 16:55 UTC, mikenath223 requested changes
### Hello @erezfree29  👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

To highlight: 
- Fix the module export in the app.
- Use es6 arrow functions.

- Please refer to other comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-06-17 11:46 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The ES6 syntax is applied appropriately



### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-21 09:48 UTC, merged